const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"科创中心",
                        "menuJump":"列表",
                        "tableName":"kechuangzuopin"
                    }
                ],
                "menu":"科创中心"
            }
			,
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"我的作品信息",
			            "menuJump":"列表",
			            "tableName":"wdkechuangzuopin"
			        }
			    ],
			    "menu":"我的作品信息"
			}
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"作品评论信息",
                        "menuJump":"列表",
                        "tableName":"kechuangzuopinLiuyan"
                    }
                ],
                "menu":"我的作品评论信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"通知公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"通知公告"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"视频信息",
                        "menuJump":"列表",
                        "tableName":"shipin"
                    }
                ],
                "menu":"视频信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"视频收藏管理",
                        "menuJump":"列表",
                        "tableName":"shipinCollection"
                    }
                ],
                "menu":"我的视频收藏"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"视频评论信息",
                        "menuJump":"列表",
                        "tableName":"shipinLiuyan"
                    }
                ],
                "menu":"我的视频评论信息"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"文章信息",
                        "menuJump":"列表",
                        "tableName":"wenzhang"
                    }
                ],
                "menu":"文章信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"文章收藏管理",
                        "menuJump":"列表",
                        "tableName":"wenzhangCollection"
                    }
                ],
                "menu":"我的文章收藏"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"文章评论信息",
                        "menuJump":"列表",
                        "tableName":"wenzhangLiuyan"
                    }
                ],
                "menu":"我的文章评论信息"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
